version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:8000"  # Updated port mapping

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://api:8000
    depends_on:
      - api
    networks:
      - app-network
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl  # SSL certificate directory
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

